# This is a basic workflow to help you get started with Actions

name: Github pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install --dev

      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://javierbecerra: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@github.com/javierbecerra/SATdle_.git
          # Prevent warnings from being treated as errors
          CI=false npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: 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
